name: NPM Publish

on:
  workflow_dispatch:
    inputs:
      versionType:
        description: "Version bump type (patch, minor, major)"
        required: true
        default: "patch"

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: npm ci

      - name: Configure Git identity
        run: |
          git config --global user.email "aj962788@gmail.com"
          git config --global user.name "AtharvaJoshi16"

      - name: Bump version
        run: |
          npm version ${{ github.event.inputs.versionType }} -m "chore(release): %s [skip ci]"
          git push --follow-tags

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTOMATION_TOKEN }}
        run: npm publish --access public
